### ISSUE TITLE
Action triggered too many times

### ISSUE THREAD

**Issue by B4nan** [apify/pull-request-toolkit-action#30]
I just created a PR in the docs repo, and got few notifications about the PR toolkit action being canceled. Looks like there were 4 actions triggered for the PR?

<img width="1440" alt="image" src="https://github.com/apify/pull-request-toolkit-action/assets/615580/e1da2cb6-4b5d-4150-b996-3c87a3e33fc6">

https://github.com/apify/apify-docs/pull/664

**Comment by B4nan** [comment]
But why do we have two different actions for this? You can see `Apify PR toolkit` and `Apify pull request toolkit` there. I can understand the second commit will retrigger it, but it feels like we have two actions for the same, maybe one is in the org and one in the repo?

**Comment by mtrunkat** [comment]
The latter one should be disabled now. It's the same action, but the first one is defined in the repo and the latter one is defined globally at the organizational level. I was just testing the organizational one and will migrate to it soon.

**Comment by mtrunkat** [comment]
Most likely fixed now -> closing
